# Generated by Django 3.0.3 on 2020-03-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quesion',
            new_name='question',
        ),
    ]
