# Generated by Django 3.0.3 on 2020-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_name', models.CharField(max_length=25)),
            ],
        ),
    ]
