# Generated by Django 3.0.3 on 2020-04-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200331_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='extra_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payoff_style',
            field=models.CharField(blank=True, default='Dave Ramsey', max_length=25, null=True),
        ),
    ]
